# Generated by Django 5.2 on 2025-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_educational_courses', '0002_course_lesson_category_enrollment_review_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории уникальное. Ограничение 15 знаков', max_length=30, unique=True, verbose_name='Название категории'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.CharField(max_length=40, verbose_name='ФИО преподавателя'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ManyToManyField(related_name='enrollments', to='api_educational_courses.course'),
        ),
    ]
