# Generated by Django 5.2 on 2025-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_educational_courses', '0003_alter_category_name_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0.0, help_text='От 1 до 10', verbose_name='Оценка'),
        ),
    ]
